---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycalculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - name: myapp
          image: teja12.azurecr.io/img12
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mycalculator-service
spec:
  type: LoadBalancer
  selector:
    app: calculator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
